import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { TestProvider } from '@/store/context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Education Platform',
  description: 'Generated by Mahmoud Saad',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TestProvider>
        {children}
        </TestProvider>
        </body>
    </html>
  )
}
